# Generated by Django 3.2.6 on 2022-05-29 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_auto_20220526_1439'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ingredientsinrecipe',
            name='unique_ingred_recipe',
        ),
        migrations.AddConstraint(
            model_name='ingredientsinrecipe',
            constraint=models.UniqueConstraint(fields=('ingredient', 'recipe'), name='unique_ingred_recipe'),
        ),
    ]
