# Generated by Django 4.0.3 on 2022-04-20 15:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorite_recipes',
            field=models.ManyToManyField(related_name='favorites', to='recipes.recipe', verbose_name='Избранные рецепты'),
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='', max_length=150, verbose_name='Пароль'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='subscribing',
            field=models.ManyToManyField(through='users.Follow', to=settings.AUTH_USER_MODEL, verbose_name='Подписчики'),
        ),
    ]
