# Generated by Django 3.2.6 on 2022-05-26 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_follow_author_alter_follow_user_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='follow',
            options={'verbose_name': 'Подписка', 'verbose_name_plural': 'Подписки'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('username',), 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
